#Pytorch Fundamentals (Libraries)


https://www.learnpytorch.io/

In [ ]:
print('Im Ganishvar')
!nvidia-smi

Im Ganishvar
/bin/bash: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.1+cu118


# Introduction to tensors


In [ ]:
# SCALAR
scalar=torch.tensor(7)
scalar
## the above is how tensors are created torch.tensor()

tensor(7)

In [ ]:
scalar.ndim  ## to get its dimensions

0

In [ ]:
scalar.item() ## gets the value of tensor

7

In [ ]:
scalar.ndim,scalar.item() ## can use comma to make it into single line

(0, 7)

In [ ]:
vector=torch.tensor([7,7]) ## creating a vector using tensor command
vector.ndim ## ndim just counts number of sq brackets

1

In [ ]:
vector.shape ## no of elements

torch.Size([2])

In [ ]:
Matrix = torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix.shape


torch.Size([2, 2])

In [ ]:
Matrix[0]

tensor([7, 8])

In [ ]:
## Tensor
Tensor=torch.tensor([[[1,2,3],[1,2,3],[4,5,6]]])
Tensor ## just like 3D array

tensor([[[1, 2, 3],
         [1, 2, 3],
         [4, 5, 6]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.shape ## 1 - is the page , 3,3 are the no
             ## of elements in that page number

torch.Size([1, 3, 3])

In [ ]:
Tensor.size() ## it shld have brackets because its a function

torch.Size([1, 3, 3])

In [ ]:
Tensor[0,2,2]

tensor(6)

# Random Tensors and Datatype Operation


Why random tensors ?  
Random tensors are important because the way many neural networks learn is that
they Start with tensors full Of random numbers and then adjust those random numbers to better represent the data.  

look at data - Start with random number-update random numbers-look at data - update random numbers





In [ ]:
random_tensor=torch.rand(3,4)
random_tensor ## 2- pages , 4 - columns , 3 - rows

tensor([[0.4860, 0.8011, 0.1721, 0.1040],
        [0.8332, 0.0206, 0.5627, 0.7530],
        [0.9357, 0.5391, 0.8575, 0.0802]])

In [ ]:
random_tensor.shape,random_tensor.ndim

(torch.Size([3, 4]), 2)

In [ ]:
random_image_size_tensor=torch.rand(size=(224,224,3)) ## can also not use size
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [ ]:
zeros=torch.zeros(3,4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype  ## we always using float

torch.float32

##Creating Ranges

In [ ]:
# Use torch.arange()
zero_to_ten=torch.arange(0,11,2)
one_to_ten=torch.arange(1,11)  ## ends at end-1
zero_to_ten,one_to_ten
## 0 - start number
## 11 - end number
## 2 - steps

(tensor([ 0,  2,  4,  6,  8, 10]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros
 # input  takes a example and we ask it to make zeros like eg thus output

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor datatypes

**Notes**= Tensor datatypes might be the biggest errors we might run into in pytorch and deeplearning eg


1. Tensors not right Datatype
2. Tensors not Right Shape
3. Tensors not on the right device



In [ ]:
float_32_tensor=torch.tensor([3,6,9],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor
##  dtype - we can specify the datatype
## device - what gpu or device we on , cuda might be better for GPU
##Required grad - to track gradients or not

tensor([3, 6, 9])

In [ ]:
float_32_tensor.dtype

torch.int64

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor ## wont throw an error

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor*int_32_tensor ## still works

tensor([ 9, 36, 81])

## Getting Tensor Info

In [ ]:
tensor=torch.rand(5,5,dtype=torch.float16)
tensor
print(f"Datatype of tensor :{tensor.dtype}")
print(f"Shape of tensor :{tensor.shape}")
print(f"Device the tensor is on :{tensor.device}")

Datatype of tensor :torch.float16
Shape of tensor :torch.Size([5, 5])
Device the tensor is on :cpu


# Tensor Operations

* Addition
* Subtraction
* Multiplication
* Divison
* Matrix Multiplication
* Matrix Dot Product

In [ ]:
# Creating a Tensor
tensor = torch.rand(2,4)
tensor

tensor([[0.2245, 0.4005, 0.9955, 0.6579],
        [0.6836, 0.3565, 0.6258, 0.0386]])

In [ ]:
## tensor Addition
tensor + 100

tensor([[100.2245, 100.4005, 100.9955, 100.6579],
        [100.6836, 100.3565, 100.6258, 100.0386]])

In [ ]:
##Tensor Multiplication ( ELEMENT WISE)
tensor * 10 , tensor * tensor

(tensor([[2.2449, 4.0054, 9.9547, 6.5787],
         [6.8361, 3.5652, 6.2583, 0.3864]]),
 tensor([[0.0504, 0.1604, 0.9910, 0.4328],
         [0.4673, 0.1271, 0.3917, 0.0015]]))

In [ ]:
## Tensor Divison
tensor / 10

tensor([[0.0224, 0.0401, 0.0995, 0.0658],
        [0.0684, 0.0357, 0.0626, 0.0039]])

In [ ]:
## Tensor Subtraction
tensor-2

tensor([[-1.7755, -1.5995, -1.0045, -1.3421],
        [-1.3164, -1.6435, -1.3742, -1.9614]])

In [ ]:
# Inbuilt PYTORCH functions
torch.mul(tensor,2)

tensor([[0.4490, 0.8011, 1.9909, 1.3157],
        [1.3672, 0.7130, 1.2517, 0.0773]])

In [ ]:
torch.add(tensor,10)

tensor([[10.2245, 10.4005, 10.9955, 10.6579],
        [10.6836, 10.3565, 10.6258, 10.0386]])

In [ ]:
# Matrix Multiplication
torch.matmul(tensor,tensor.T)
## INNER DIMENSION SIZE SHOULD MATCH
## OUTER DIMENSION IS THE OUTPUT SIZE

tensor([[1.6346, 0.9447],
        [0.9447, 0.9876]])

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value  += tensor[i]*tensor[i]
print(value)


tensor([0.5177, 0.2875, 1.3826, 0.4343])
CPU times: user 1.06 ms, sys: 1.01 ms, total: 2.06 ms
Wall time: 2.45 ms


In [ ]:
%%time
torch.matmul(tensor,tensor.T) ##just to see the compilation speed

CPU times: user 148 µs, sys: 0 ns, total: 148 µs
Wall time: 358 µs


tensor([[1.6346, 0.9447],
        [0.9447, 0.9876]])

In [ ]:
## Transpose of Matrix
tensor_A = torch.rand(2,3)
tensor_A

tensor([[0.0419, 0.8936, 0.5664],
        [0.7755, 0.5028, 0.8755]])

In [ ]:
tensor_AT=tensor_A.T  ## Transpose
tensor_AT

tensor([[0.0419, 0.7755],
        [0.8936, 0.5028],
        [0.5664, 0.8755]])

# Tensor Aggregation and Numpy Usage

## Finding Max , min , mean , sum and issue in type conversion

In [ ]:
## creating a Tensor
x=torch.arange(0,101,10)
x


tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
## Min and Max
torch.min(x) , torch.max(x)

(tensor(0), tensor(100))

In [ ]:
x.min(),x.max()

(tensor(0), tensor(100))

In [ ]:
# Mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
## cannot run this code without Type conversion

(tensor(50.), tensor(50.))

In [ ]:
#finding the Sum
torch.sum(x) , x.sum()

(tensor(550), tensor(550))

## Positional min , max ( the index )

In [ ]:
## arg just sends back the index
x.argmin() , x.argmax()

(tensor(0), tensor(10))

In [ ]:
x[5] ## getting the value

tensor(50)

## Reshaping , Stacking , Squeezing , Un-Squeezing

* Reshape - Reshapes an input tensor to defined shape
* View - Return view of input tensor of certain shape but keep same memory as original tensor
* Stacking - combine Multiple tensors on top of each other ( specific ways are there including vstack , hstack , (vertical and horizontal ) )
* Squeeze - Removes all '1' dimension from a tensor
* Unsqueeze - Add a '1' dimension to a tensor
* Permute - return a view of input with dimensions permuted (swapped) in a certain way

In [ ]:
#Tensor Creation
import torch
x=torch.arange(1.,11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
 #Reshaping
 x_reshaped=x.reshape(2,5)
 x_reshaped  ## should match the inital size

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
# View
z = x.view(2,5)
z,z.shape   # view is just viewing it in diff perspective , no changes wll happen to the element

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# Stacking
x_stacked=torch.stack([x,x,x],dim=1)  ## if Dim = 0 , vertically it stacks
x_stacked      ## if dim = 1 , it stacks into group of 3 with each first element in one tensor

tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.]])

In [ ]:
## squeeze
sq=x_reshaped.squeeze()
## removes extra dimensions


In [ ]:
sq.shape

torch.Size([2, 5])

In [ ]:
## Unsqueeze
usq=x_reshaped.unsqueeze(dim=0)
 ## need to specify the dimension vertical or horizontal

In [ ]:
usq.shape

torch.Size([1, 2, 5])

In [ ]:
# permute - rearranges dimensions of tensor in a order
x_original = torch.rand(size=(223,224,3)) ## axis is in order 0 , 1 , 2
x_permuted = x_original.permute(2,1,0)
## new axis are swapped like 0->1 , 1->2 , 2->0
x_original.shape ,x_permuted.shape


(torch.Size([223, 224, 3]), torch.Size([3, 224, 223]))

## Indexing ( Data Pulling )

In [ ]:
# Indexing is similar to Numpy Indexing
import torch
x=torch.arange(1,10,1).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
print(x[0])
print(x[0,0])
print(x[0][0][0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [ ]:
print(x[:,1,1])
print(x[:,:,1])
print(x[0,:,:])

tensor([5])
tensor([[2, 5, 8]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


## Array

In [ ]:
import torch
import numpy as np

array =np.arange(1.0,10.0)
tensor=torch.torch.from_numpy(array)
## when converting from numpy to pytorch , it takes float 64 unless changes or converted
array,tensor


(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
#Changing array value
array = array + 1
array , tensor
# tensor doesnt change as it gets array values and doesnt depend on array anymore

(array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
#tensor to numpy array changing
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#changing tensor
tensor = tensor+1
tensor , numpy_tensor # doesnt change array and datatype

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducablity

Learning Process of a Neural Network
Start with random number -> tensor operation -> update random numbers into better representation-> again ,again , again...

To reduce Randomness in neural networks and pytorch , comes the concept of a **random seed**
It flavours the randomness


In [ ]:
import torch
# Creating rand tensors
x=torch.rand(3,3)
y=torch.rand(3,3)
print(x)
print(y)
print(x == y)

tensor([[0.5030, 0.9810, 0.5805],
        [0.2296, 0.2839, 0.6700],
        [0.4229, 0.2355, 0.6728]])
tensor([[0.9264, 0.3814, 0.4671],
        [0.4023, 0.4214, 0.5353],
        [0.7502, 0.5538, 0.1715]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [ ]:
# Creating Random but reproducable tensors
import torch

# Set random seed ( just like minecraft seed)
Random_seed=1
torch.manual_seed(Random_seed)
a=torch.rand(3,5)
# just like minecraft , seed number = same map for 2 players
# call it everytime we use a torch rand
torch.manual_seed(Random_seed)
b=torch.rand(3,5)
print(a)
print(b)
print(a==b)

tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544, 0.5695, 0.4388],
        [0.6387, 0.5247, 0.6826, 0.3051, 0.4635]])
tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544, 0.5695, 0.4388],
        [0.6387, 0.5247, 0.6826, 0.3051, 0.4635]])
tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


# GPU Running

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device ="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor=torch.rand(2,3)
tensor # tensr is on cpu from seen in output
print(tensor,tensor.device)

tensor([[0.5016, 0.9033, 0.6065],
        [0.2184, 0.7985, 0.2253]]) cpu


In [ ]:
#moving tensors to gpu from cpu
tensor_gpu=tensor.to(device)
tensor_gpu

tensor([[0.5016, 0.9033, 0.6065],
        [0.2184, 0.7985, 0.2253]], device='cuda:0')

In [ ]:
tensor_back_cpu=tensor_gpu.cpu().numpy()
tensor_back_cpu

array([[0.50159043, 0.90326977, 0.6064714 ],
       [0.21837002, 0.7984841 , 0.22526914]], dtype=float32)

# Exercises and Extra - Curriculum

https://www.learnpytorch.io/00_pytorch_fundamentals/